### PR TITLE
Codedcoder

### PR DESCRIPTION
**Pull request by codedCoderr**
@Vectormike changes effected

### CODE REVIEW

**Comment by mikeattara** [comment]
@codedCoderr Kindly resolve the merge conflicts

**Comment by codedCoderr** [comment]
i'm having difficulty fixing this conflict

**Comment by mikeattara** [comment]
@codedCoderr Can we have a video chat around 11am?

**Comment by codedCoderr** [comment]
I can see that. How do i resolve it?Tried all i can

**Comment by codedCoderr** [comment]
Voice chat,sure.

**Comment by mikeattara** [comment]
Kindly install https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare
So we can collaborate and fix it in real time

**Comment by codedCoderr** [comment]
when are we starting collaboration?

**Comment by mikeattara** [comment]
11am

**Pull request merged**
